name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to macOS or Windows if needed

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version according to your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: |
          npx playwright install

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright test
